name: Sketchbot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  flutter_tesseract_ocr: ^0.3.0
  image_picker: ^0.8.4+4
  http: ^1.2.0
  convert: ^3.1.1
  pretty_diff_text: ^2.0.0
  undo: ^1.5.0
  speech_to_text: ^6.6.2
  google_mlkit_digital_ink_recognition: ^0.12.0
  diff_match_patch: ^0.4.0
  google_generative_ai: ^0.4.6
  flutter_tts: ^3.4.0
  flutter_screen_recording: ^2.0.17
  intl: ^0.19.0
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  
